language: java
jdk:
  - openjdk6
  - openjdk7
#  - oraclejdk7
#  - oraclejdk8
# whitelist
branches:
  only:
    - master
notifications:
  email: false
after_success:
  - mvn cobertura:cobertura coveralls:report
